### ISSUE TITLE
New key!!

### ISSUE THREAD

**Issue by MambaBoyy** [nirajxhrestha/VmWare-Workstation-Keys#1]
I used this keys
ZF3R0-FHED2-M80TY-8QYGC-NPKYF
YF390-0HF8P-M81RQ-2DXQE-M2UT6
ZF71R-DMX85-08DQY-8YMNC-PPHV8
[https://gist.github.com/williamgh2019/cc2ad94cc18cb930a0aab42ed8d39e6f](url)

**Comment by nirajxhrestha** [comment]
thank you will add it @MambaBoyy
